name: C/C++ CI

on:
  push:
    branches: [ master* ]
  pull_request:
    branches: [ master* ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: WHY DO I NEED TO DO THIS
      run: sudo su
    - name: configure
      run: sudo ./configure.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
